pipeline {
    agent any // Use any available agent
    // no triggers, only manual builds

    stages {
        stage('Checkout') {
            steps {
                // Pull the repo from Github
                git(
                    url: 'https://github.com/youssefelghamour/alx-backend-python.git',
                    branch: 'main',
                    credentialsId: 'github-credentials'
                )
                sh 'git branch'       // just show the current branch
            }
        }

        stage('Install dependancies') {
            steps {
                sh '''
                /usr/bin/python3 -m venv venv
                . venv/bin/activate
                pip3 install -r messaging_app/requirements.txt
                # Install pytest and HTML report plugin
                pip install pytest pytest-html
                '''
            }
        }

        stage('Run tests') {
            steps {
                dir('messaging_app') { // cd into messaging_app directory
                    // DB credentials are stored securely in Jenkins Credentials, not in the repo
                    withCredentials([
                        usernamePassword(credentialsId: 'db_credentials', usernameVariable: 'DB_USER', passwordVariable: 'DB_PASS'),
                        string(credentialsId: 'db_name', variable: 'DB_NAME'),
                        string(credentialsId: 'db_host', variable: 'DB_HOST'),
                        string(credentialsId: 'db_port', variable: 'DB_PORT')
                    ]) {
                        sh '''
                        . venv/bin/activate
                        export PYTHONPATH=$PWD
                        export DJANGO_SETTINGS_MODULE=messaging_app.settings
                        export DB_NAME=$DB_NAME
                        export DB_USER=$DB_USER
                        export DB_PASSWORD=$DB_PASS
                        export DB_HOST=$DB_HOST
                        export DB_PORT=$DB_PORT
                        export DJANGO_SETTINGS_MODULE=messaging_app.settings
                        # Run tests and generate an HTML report
                        # ([ $? -eq 5 ] && exit 0 || exit $?): allows pytest to pass even if no tests are collected (code 5) exit with 0 = pass, otherwise fail build on test fails
                        pytest chats/test/jenkins_tests/ --html=report.html --self-contained-html || ([ $? -eq 5 ] && exit 0 || exit $?)
                        '''
                    }
                }
            }
            post {
                always {
                    dir('messaging_app') {
                        // Archive the test report for download in Jenkins
                        archiveArtifacts artifacts: 'report.html', fingerprint: true
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('messaging_app') {
                    sh 'docker build -t youssefelghamour/messaging-app:latest .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker tag youssefelghamour/messaging-app:latest youssefelghamour/messaging-app:jenkins
                    docker push youssefelghamour/messaging-app:jenkins
                    '''
                }
            }
        }
    }
}