pipeline {
    agent any // Use any available agent
    // no triggers, only manual builds

    stages {
        stage('Checkout') {
            steps {
                // Pull the repo from Github
                git(
                    url: 'https://github.com/youssefelghamour/alx-backend-python.git',
                    branch: 'main'
                )
            }
        }

        stage('Install dependancies') {
            steps {
                dir('messaging_app') { // cd into messaging_app directory
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    # Install pytest and HTML report plugin
                    pip install pytest pytest-html
                    '''
                }
            }
        }

        stage('Run tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                    . venv/bin/activate
                    # Run tests and generate an HTML report
                    pytest --html=report.html --self-contained-html
                    '''
                }
            }
            post {
                always {
                    dir('messaging_app') {
                        // Archive the test report for download in Jenkins
                        archiveArtifacts artifacts: 'report.html', fingerprint: true
                    }
                }
            }
        }
    }
}