pipeline {
    agent any // Use any available agent
    // no triggers, only manual builds

    stages {
        stage('Checkout') {
            steps {
                // Pull the repo from Github
                git(
                    url: 'https://github.com/youssefelghamour/alx-backend-python.git',
                    branch: 'main'
                )
            }
        }

        stage('Install dependancies') {
            steps {
                dir('messaging_app') { // cd into messaging_app directory
                    sh '''
                    /usr/bin/python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    # Install pytest and HTML report plugin
                    pip install pytest pytest-html
                    '''
                }
            }
        }

        stage('Run tests') {
            steps {
                dir('messaging_app') {
                    // DB credentials are stored securely in Jenkins Credentials, not in the repo
                    withCredentials([
                        usernamePassword(credentialsId: 'db_credentials', usernameVariable: 'DB_USER', passwordVariable: 'DB_PASS'),
                        string(credentialsId: 'db_name', variable: 'DB_NAME'),
                        string(credentialsId: 'db_host', variable: 'DB_HOST'),
                        string(credentialsId: 'db_port', variable: 'DB_PORT')
                    ]) {
                        sh '''
                        . venv/bin/activate
                        export DJANGO_SETTINGS_MODULE=messaging_app.settings
                        export DB_NAME=$DB_NAME
                        export DB_USER=$DB_USER
                        export DB_PASSWORD=$DB_PASS
                        export DB_HOST=$DB_HOST
                        export DB_PORT=$DB_PORT
                        export DJANGO_SETTINGS_MODULE=messaging_app.settings
                        # Flag to tell Django tests to use in-memory SQLite on Jenkins
                        export JENKINS=1
                        # Run tests and generate an HTML report
                        pytest --html=report.html --self-contained-html
                        '''
                    }
                }
            }
            post {
                always {
                    dir('messaging_app') {
                        // Archive the test report for download in Jenkins
                        archiveArtifacts artifacts: 'report.html', fingerprint: true
                    }
                }
            }
        }
    }
}