apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: ClusterIP
  selector:
    app: django-app
    version: blue  # initially routes to blue deployment, then changed to green
  ports:
  - port: 8000
    targetPort: 8000
